name: Generate Snake Game

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate the snake game files
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          # GitHub username to fetch the contribution graph from
          github_user_name: ${{ github.taniatitiriga }}

          # List of files to generate with customizable options
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Upload the generated files to GitHub Pages
      - name: Push Snake Game to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
